name: PHP Unit Tests

on: [ push, pull_request ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Composer Install
        uses: php-actions/composer@v6

      - name: Run PHPUnit for PHP 7.3
        uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          version: 9.5
          php_version: 7.3
          memory_limit: 256M

      - name: Run PHPUnit for PHP 7.4
        uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          version: 9.5
          php_version: 7.4
          memory_limit: 256M

      - name: Run PHPUnit for PHP 8.0
        uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          version: 9.5
          php_version: 8.0
          memory_limit: 256M

      - name: Run PHPUnit for PHP 8.1
        uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          version: 9.5
          php_version: 8.1
          memory_limit: 256M